branch-defaults:
  master:
    environment: krono-train-dev
    group_suffix: null
global:
  application_name: krono_train
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
